# PHP CircleCI 2.0 configuration file

version: 2
jobs:
  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Docker Build
          command: docker build -t lanopsdev/monitoring-graf-db .
      - run:
          name: Docker Up
          command: docker run lanopsdev/monitoring-graf-db
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Docker Build
          command: |
            docker build -t lanopsdev/monitoring-graf-db:$CIRCLE_TAG .
      - run:
          name: Upload to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME  -p $DOCKERHUB_PASSWORD
            docker push lanopsdev/monitoring-graf-db:$CIRCLE_TAG
workflows:
  version: 2
  # Un-Tagged builds
  test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
  # Tagged Builds
  test-and-build:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
